### PR TITLE
Test with tox

### PR DESCRIPTION
**Pull request by adamchainz**
Simpler and more predictable than self-managing a virtualenv. I've set it up to allow arguments to be passed through to `pytest` by running e.g. `tox -- -f`.

### CODE REVIEW

**Comment by adamchainz** [comment]
This currently includes the contents of #1 , which should be merged first

**Comment by ryansb** [comment]
This has been merged as https://github.com/ryansb/cfn-wrapper-python/commit/5e84b5bd383fada1f26831a1268779e73270d4d7

**Comment by ryansb** [comment]
I had to make small modifications to make coverage reports appear across test runs.

**Comment by adamchainz** [comment]
Since this took a long time, we forked it to https://github.com/timeoutdigital/cfn-resource-timeout

We'd be happy for you to reconcile the changes though

**Comment by ryansb** [comment]
Very understandable. I've also added Python 3.6 support, so it may be a bit of a task to reconcile them. 

I notice the fork has a dependency on `requests` which I don't think I can pull back upstream, since I know some people copy/paste `cfn_resource.py` into the inline code for CloudFormation templates. That means extra libs are a no-go.

If you'd like, I can add you as a contributor here and we can work on adding back all the Travis + new tests in your fork. The only thing is I don't think I could bring back all the changes due to the extra dep. Lmk what you think.

**Comment by adamchainz** [comment]
We can depend on requests, at `botocore.vendored.requests` (or whatever the exact path is)

Wouldn't mind being a contributor :)

**Comment by ryansb** [comment]
Ooooh, I didn't think of scooping the botocore vendored version. That's crafty of you!

**Pull request closed without merging**
